### ISSUE TITLE
Add periodical heart beats from leaders to followers

### ISSUE THREAD

**Issue by HagarMeir** [hyperledger-labs/SmartBFT#109]

**Comment by tock-ibm** [comment]
In the absence of requests, the leader may fail without anyone noticing until the next requests comes along, and triggers a timeout.

Create a mechanisms in which in the absence of requests the leader broadcasts periodic heartbeats. Followers maintain a heartbeat timeout timer, that is extended when a heartbeat is received. When a heartbeat expired the followers complain and start a view change process.

When requests are submitted, heartbeats should not be sent, and timeouts extended when requests are received (Backlog).
