### ISSUE TITLE
WAL: extend header to 64bit length & 64bit crc

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#112]
Currently the header is 32bit length + 32bit CRC.

Make the header two 8 byte words (i.e. 16B) instead of one. 
First word should include 56 bits of length, and the upper 8 bits should be reserved for future use,  and reset to 0' by default. In the future, their use may include version bits to enable a change in the wire format in some future release.
The second word should be a 64bit CRC.

**Comment by yacovm** [comment]
If I'm not mistaken, [etcd/raft uses 32 bits](https://github.com/etcd-io/etcd/blob/master/pkg/crc/crc.go). 
I think if they haven't upgraded to 64 bits then there is little justification to be extra prudent than them.
