### ISSUE TITLE
Add support for view change in the recovery 

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#149]
Currently, we only have code that recovers a view from WAL, however we also need to be able to recover the view changer from WAL, and also to be able to persist view changes inside the WAL.

**Comment by HagarMeir** [comment]
https://github.com/SmartBFT-Go/consensus/pull/338

**Comment by HagarMeir** [comment]
https://github.com/SmartBFT-Go/consensus/pull/344
