### ISSUE TITLE
Monotonic sequence number on client requests to avoid replay attacks.

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#168]
In the BFT-Smart protocol, client requests carry a monotonically increasing sequence number. The library then enforced that incoming TXs have TX.sqn > last.sqn (actually TX.sqn = last.sqn+1, but that is not essential.) (See: Sousa & Bessani, EDCC'12, Algo-2).

This is used to avoid replay attacks. 

Currently the types.RequestInfo carries a {ClientID string, TxID string}. 
The client is in charge of providing unique RequestInfo with every request.

In Fabric a replay attack will cause the TX to be included in a block but the TX will fail validation. Therefore in Fabric this does not affect safety, but presents a resource problem.

One proposal: add a third field: sequence uint64, 
If this field is 0, ignore the issue of these kind of replay attacks, 
If this field is >0, enforce this rule.

Another option would be to design another mechanism to prevent this kind of attack using the current structure .

**Comment by C0rWin** [comment]
First of all I think while we do need to keep Fabric in mind we should strive to build a general purpose BFT library which will answer to broader specification. 

Also, how is that different from #75? It seems duplicating it.

**Comment by tock-ibm** [comment]
> First of all I think while we do need to keep Fabric in mind we should strive to build a general purpose BFT library which will answer to broader specification.
> 
> Also, how is that different from #75? It seems duplicating it.

True, it is related to #75, however here I cite the solution proposed by BFT-Smart. I'll mark as duplicate.

**Comment by C0rWin** [comment]
Since this is duplicate, I'd rather to close it and put reference into #75 so we can citation linkable
