### ISSUE TITLE
Test: a test framework for end-to-end consensus tests 

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#175]
Implement a test framework that would allow the testing of complex scenarios with multiple consensus instances.

A network emulation using some mock implementation, e.g.
- channels from point to point, or direct queues
- allow to simulate partitions, asymmetric network behaviors, etc

A set of nodes, that allows 
- to shut down and start nodes
- simulate byzantine behaviors, etc

**Comment by yacovm** [comment]
done
