### ISSUE TITLE
Implement dynamic reconfiguration support: Discussion

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#184]
We should be able to:

- Add new nodes 
- Remove existing nodes

Since this is user triggered, and as a lesson learned from implementations of earlier consensus systems, we should do the application reconfiguration along with the consensus configuration.

This means, that the application should propose a request with an additional input: the metadata of the next view. 

The view metadata will contain not only the proposal sequence and the view number, but also: 
- **N** (the number of nodes)
- A list of node IDs (integers)

This doesn't add a considerable overhead, and simplifies the configuration. 

 As a result of the commit of the transaction, the view number will increase by some **k > 0** (according to the metadata specified in the special request),  the current view will halt, and the controller will spin a new view. 

This has the following desirable effect: If the current leader needs to be taken offline to maintenance, we can trigger a configuration change that simply doesn't change N, and as a result - a view change occurs gracefully and immediately after the commit of the proposal. 

The reason for specifying a **k** and not just always incrementing the view number by 1, is that:

- In case we add a new node, we don't want to view change to a view where it is the leader, but instead perhaps we'd want to keep the leader what it is now.
- In case we remove a node, we may also want to keep the leader to be what it is now. 

Also, note that since we rely on the existence of a synchronization mechanism that the application provides, we don't need consent of the members of the new view if we add an assumption that when we add a new node, it is considered "offline" until it catches up with the cluster, and the end-user is aware of the repercussions and dangers (say, when we increase from 4 to 5 nodes, the quorum size increases by 1, **f** stays 1,  however: the newly added node is considered offline, and thus we are implicitly violating our failure assumptions for the time it is catching up with the cluster).

If the end-user wants better reliability with reconfiguration, it can run 7 nodes and support 2 failures at steady-state, and 1 failure at time of reconfiguration. 
In later stages of the project, we perhaps could implement something that does achieve consensus from the next view by first synchronizing itself with the cluster. 

Opinions?

**Comment by HagarMeir** [comment]
https://github.com/SmartBFT-Go/consensus/pull/417
