### ISSUE TITLE
Consensus cleanup: Start() should return an error and validate the configuration 

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#189]
Start should return an error rather than a "Future".
Start should validate the configuration before starting the internal components.

**Comment by yacovm** [comment]
I think we should open this only once we have a configuration object and then re-assess.

**Comment by tock-ibm** [comment]
Then why close? put it in the backlog and todo column

**Comment by C0rWin** [comment]
Though in general I do agree we need to validate configuration, I think that start should provide a functionality to attest that cluster is indeed up and running and Future seems like a good abstraction here.

If there is a path during the start which might cause an error or improper condition it make sense probably to add error, while configuration should be checked beforehand.
