### ISSUE TITLE
Don't print proposals/pre-prepares or commit contents in logs

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#221]
We shouldn't do that as logs might end up in places where the data isn't authorized to reside.

**Comment by C0rWin** [comment]
we might still consider to do it with debug level, assuming no one will run production code with debug mode on.

**Comment by yacovm** [comment]
I'm not sure I agree, as I don't think there is any useful information that can be printed in the content of the proposals. If anything - it's sensitive information that might leak into log analysis systems and end up god knows where ;-) 

I think the robust approach would be to ask from the application an interface that stingifies (String()) proposal contents, but for now we can just not print them, and print only their lengths.
