### ISSUE TITLE
Make request pool use a scheduler

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#242]
have a ticker emit time into a channel, and another thread read the time and scan events for deadline.

Possible advantage - better control of timing in tests, we can speed-up or slow down time as we wish. 

On the other hand this is more complicated, and has no clear benefit in production.

This can be applied to both RequestPool and Heartbeat monitor.

**Comment by tock-ibm** [comment]
See #109 and discussion on #240

**Comment by yacovm** [comment]
Update: Now the heartbeat monitor uses a time channel, and all we are left is to make the request pool use a scheduler.
