### ISSUE TITLE
Add support for dynamic runtime configuration changes

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#317]
We should be able to change stuff like batch timeout and heartbeats dynamically without needing to restart the library instance.

The best course of action is to have a function that returns the configuration, instead of the configuration being injected once at construction.

**Comment by HagarMeir** [comment]
https://github.com/SmartBFT-Go/consensus/issues/184#issue-473627085

**Comment by HagarMeir** [comment]
The current proposal for reconfiguration support is as follows:

When the library calls `Deliver` the application will return an object of type `Reconfig`  which states if the last delivered proposal was a reconfiguration and if so the object includes the latest configuration and set of nodes (membership). 

`Sync` will return an object of type `LatestState` including the last `Decision` (as the `Sync` returned before) and a `Reconfig` over this last `Decision`.

The library, after receiving a reconfiguration notice, will abort the current view and advance the view number by `N`, the new number of nodes, in the hope of continuing with the same leader.

**Comment by HagarMeir** [comment]
https://github.com/SmartBFT-Go/consensus/pull/417
