### ISSUE TITLE
Make batcher honor total batch size in terms of megabytes as well as transaction count. 

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#327]

**Comment by tock-ibm** [comment]
Fabric has a configuration parameter:

message BatchSize {
    // Simply specified as number of messages for now, in the future
    // we may want to allow this to be specified by size in bytes
    uint32 max_message_count = 1;
    // The byte count of the serialized messages in a batch cannot
    // exceed this value.
    uint32 absolute_max_bytes = 2;
    // The byte count of the serialized messages in a batch should not
    // exceed this value.
    uint32 preferred_max_bytes = 3;
}

 we need to be compatible with that.
