### ISSUE TITLE
Flaky TestRestartFollowers

### ISSUE THREAD

**Issue by HagarMeir** [hyperledger-labs/SmartBFT#339]
https://api.travis-ci.com/v3/job/233901127/log.txt

I think the issue is that sometimes a preprepare message is missed by a node that is being restarted, and so that node does not deliver this proposal, but the test anyway waits for it to deliver. 
Maybe we should wait for a few proposals to be delivered by the leader before waiting for all followers that were restarted to deliver. This why the followers can sync if they see they missed something.

**Comment by yacovm** [comment]
But the goal of the test is to test that they get it not via sync, since we have other tests for sync, no?

**Comment by HagarMeir** [comment]
So if they missed the prePrepare how would they deliver this proposal?
