### ISSUE TITLE
Use logical time for batch timeout.

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#340]
Currently the batcher uses 

timeout := time.After(b.batchTimeout)

for timeout, need to use logical time or the task scheduler that uses logical time.

**Comment by yacovm** [comment]
I can reason why we can use a function that mocks time, like to mock **time.After** or something but I'm not sure we need to use the task scheduler in the production code. 

We never test in integration tests anything that has to do with batch timeout, and we always use small timeouts anyway.
