### ISSUE TITLE
Batcher may pack duplicate requests in a batch

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#341]
Say you have a remainder, when you call NextBatch(),
and then you call buildBatch() and ask for more items from the pool, and append them.
The prefix of the slice you get from the pool contains the same requests you already have in the remainder, i.e. in the currentBatch.

The only time a Batcher starts with remainder, is when BatchRemainder is called on it, and this happens in two places:
1. after pruning:
(c *Controller) maybePruneRevokedRequests()

2. if the Assembler returns a remainder:
AssembleProposal(metadata []byte, requests [][]byte) (nextProp bft.Proposal, remainder [][]byte)

**Comment by tock-ibm** [comment]
I think we can get rid of the remainder concept: every time the batcher needs requests it will ask the pool for an array of requests that meets certain criteria (count, size).

**Comment by yacovm** [comment]
What if we just make *NextRequests* in the request pool, remove requests and not just return them?

**Comment by yacovm** [comment]
and, what you're basically saying is that since we anyway prune requests from request pool upon commit then we are going to prune anyway whatever we proposed, so what is left in the req. pool is effectively the reminder?
