### ISSUE TITLE
Failure in test  TestMultiLeadersPartition

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger-labs/SmartBFT#359]
[make.log.tar.gz](https://github.com/SmartBFT-Go/consensus/files/3639768/make.log.tar.gz)

**Comment by HagarMeir** [comment]
I hope this helps
https://github.com/SmartBFT-Go/consensus/pull/360
please try again (on the new master) and tell me if this still happens
because it doesn't show on my machine
