### ISSUE TITLE
Leader rotation with minimizing failures. 

### ISSUE THREAD

**Issue by yacovm** [hyperledger-labs/SmartBFT#421]
## Problem statement
Let's assume we wish to rotate leaders in some manner (for instance, round robin).
At any given time, we can have up to **f** nodes that are offline. 

If its the turn of an offline node to be the leader, we would wait for a view change to occur. 
The time to detect such a view change impairs the throughput of the system when considering a time frame where all nodes have been given a chance to be leaders. 

As a cumulative example, let's assume every node can propose blocks in a rate of **2,000** transactions per second. 
If only the **2f+1** online nodes are proposing blocks, then during a time-frame of **8** minutes (**480** seconds) the throughput would be **2,000 * 480** which is roughly **1 million** transactions.

However, if all **3f+1** nodes are given a chance to propose blocks, and the time to detect an offline node is **20** seconds, then if we rotate a leader every **T** seconds, an entire cycle during which we rotate through all nodes would take **20*f + (2f+1)T** seconds. 
If **T** is **60** seconds, then in a cluster of **10** nodes with **f=3** we get **60 + 7 * 60 = 8 * 60 = 480** seconds. However, only **7 * 60** of this time is spent doing progress, thus we get a **12.5%** reduction in throughput. 
If we rotate leaders more frequently, every 20 seconds, then we get **60 + 7 * 20 = 200** seconds for a cycle, and during this time - we only work for **140** seconds which is a **30%** reduction in throughput. 

Thus it's evident that _effective_ frequent leader rotation (every few blocks) cannot be achieved without skipping the offline nodes, unless we shorten the time to view change due to transaction omission or heartbeat inactivity, which might cause false negatives. 

One might argue that frequent leader rotation is critical for fairness, otherwise malicious parties can schedule transactions of some parties over others without any repercussions. 

## Proposed solution
Thus I propose that we maintain a "black-list" of nodes that do not become leaders as long as they are in the black-list. They still participate in consensus as any other nodes that are not black-listed.

Nodes are introduced into the black-list once a view change occurs that moves the leadership from them to other nodes.

These black-listed nodes, once they come back online - are removed from the black list in the following manner:

- Since they participate in consensus, they send prepare messages to other nodes.
- Every honest node that receives a prepare from these nodes, indicates in its commit message (which, as we know - is signed) that he has seen a prepare from that node since the last view change where it was black-listed.
- The leader of the next proposal sends a pre-prepare that contains: 
   - Header - contains application related data digest.
   - Payload - contains application related data.
   - Metadata (contains consensus specific information such as proposal sequence number, leader ID, and view number)
   - (**New field**) Last **2f+1** (signed) commits it collected from the previous committed block. 

If there are **f+1** commits that attest for seeing that offline node among the **2f+1** commits, then the node is removed from the black-list by everyone that commits that block. 

Additionally and similarly, since upon a view change, the leader sends a **NewView** message that contains at least **2f+1** signed **ViewData** messages, then it is safe to remove the said nodes from the black-list. 

Since in order to black-list a node, we need a view change to occur, but a view change also ends with **2f+1** signed **ViewData** messages from different nodes that indicate their aliveness, then we are guaranteed that at any given point in time, there are at most **f** black-listed nodes.

**Comment by HagarMeir** [comment]
The proposed solution is nice. 
I suggest we use only the **NewView** and **ViewData** messages to remove nodes from the blacklist, instead of adding more info to the proposal and changing the normal view process.
It is ok to leave a node in the blacklist until the next view change.

**Comment by yacovm** [comment]
What is the reason for restricting to only doing it based on view changes? Complexity? Performance? 

**Complexity** wise I don't think that once we implement a black list and leader rotation and black list maintenance based on view change, doing it also based on proposal doesn't complicate the solution by much, and it's also easier to test than the view change case since the effect is immediate. 

**Performance** wise, note that once we implement certificate references in the Fabric side, including the commits in the proposal message will have minimal effect on its size, as the certificates are going to be removed from it and be replaced by integers. 

There is a benefit in re-introducing revived nodes into the periodical rotation that I think might be worth the extra effort. 
If you have **f** nodes that crashed and then revived, you might reach a situation where they will never be leaders for a very long time, and then they do not propose blocks and also do not carry the burden of the high communication complexity, which incentivizes companies that host the node to crash it temporarily in order to always be a follower and save network bandwidth costs.
