### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by HagarMeir** [hyperledger-labs/SmartBFT#49]
Implement and test client's request timeouts.
The first timeout will cause only a send of the request to the leader, the second timeout will start a view change.

**Comment by HagarMeir** [comment]
Implement only the first timeout
before there is an implementation of view change

**Comment by tock-ibm** [comment]
Implemented:
first timeout triggers a forwarding to the leader.
second timeout calls complain.
third timeout auto removes the request.

The Pool has unit tests.
The first timeout is also tested with the example/naive_chain/chain_test.go

**Comment by tock-ibm** [comment]
Done.
