### ISSUE TITLE
communication layer implementation

### ISSUE THREAD

**Issue by XiaoYaoCSC** [hyperledger-labs/SmartBFT#497]
The code in examples and test seem to use channels to simulate communication between nodes. What socket library are used in the real testbed experiment in the paper?

**Comment by yacovm** [comment]
> The code in examples and test seem to use channels to simulate communication between nodes. What socket library are used in the real testbed experiment in the paper?

The [paper](https://smartbft-go.github.io/paper.pdf) experiments with the library integrated with Hyperledger Fabric, so the communication [library](https://github.com/hyperledger/fabric/tree/main/orderer/common/cluster) is gRPC over mutual TLS.

**Comment by XiaoYaoCSC** [comment]
Thanks~ 
In the paper there are 700 concurrent clients, so what is the transaction sending frequency of each client? From Figure 7, the tps is about 2000(12000) in BFT(Raft), thus the sending frequency of each client is about 3(20)  tx/s? Is that correct? Thanks again~

**Comment by yacovm** [comment]
> Thanks~ In the paper there are 700 concurrent clients, so what is the transaction sending frequency of each client? From Figure 7, the tps is about 2000(12000) in BFT(Raft), thus the sending frequency of each client is about 3(20) tx/s? Is that correct? Thanks again~

I don't remember what it was. The evaluation was done a few years ago, I think in 2020.
