### ISSUE TITLE
repository changes

### ISSUE THREAD

**Issue by pfi79** [hyperledger-labs/SmartBFT#575]
I suggest we clean up a bit:
1. remove the brunch "master"
2. rename "v2" to "main"
3. remove unnecessary brunches (I need a list of those that should be kept).
4. close unnecessary issues

questions, suggestions, comments?

**Comment by yacovm** [comment]
I'm fine with that. 

Take into consideration that having a single branch would also implicitly lock the consumer facing API of the library.

**Comment by pfi79** [comment]
@ryjones how to get rights to change or rename the default branch

**Comment by ryjones** [comment]
do it to it
